jobs:
  - job: ParallelWindows
    # Matrix strategy to run builds across different OS and MATLAB release combinations
    strategy:
      parallel: 3
    pool:
      vmImage: windows-latest
    steps:
      # Install MATLAB and required products
      - task: InstallMATLAB@1
        inputs:
          release: R2025a
          products: MATLAB_Compiler_SDK MATLAB_Test Simulink_Test

      - powershell: .\DistributeTests.ps1 
        displayName: 'PowerShell Script to distribute tests'

      - script: |
          echo $(MLM_LICENSE_TOKEN)
        env:
          MLM_LICENSE_TOKEN: $(MLM_LICENSE_TOKEN)
      
       # Download matlab-batch.exe for Windows
      - powershell: |
          Invoke-WebRequest -Uri "https://ssd.mathworks.com/supportfiles/ci/matlab-batch/v1/win64/matlab-batch.exe" -OutFile "matlab-batch.exe"
        displayName: 'Download matlab-batch for Windows'

      - script: |
           matlab-batch.exe "runtests($(MATLABTestFiles))"
        env:
          MLM_LICENSE_TOKEN: $(MLM_LICENSE_TOKEN)

  - job: ParallelLinux
    # Matrix strategy to run builds across different OS and MATLAB release combinations
    # strategy:
    #   parallel: 3
    pool:
      vmImage: ubuntu-latest
    steps:
      # Install MATLAB and required products
      - task: InstallMATLAB@1
        inputs:
          release: R2025a
          products: MATLAB_Compiler_SDK MATLAB_Test Simulink_Test

      - bash: chmod +x  DistributeTests.sh && ./DistributeTests.sh
        displayName: 'Bash Script to distribute tests'

      - script: |
          echo $(MATLABTestFiles)

      # Download matlab-batch for Linux
      - bash: |
          curl -L "https://ssd.mathworks.com/supportfiles/ci/matlab-batch/v1/glnxa64/matlab-batch" -o matlab-batch
          chmod +x matlab-batch
          ./matlab-batch "runtests($(MATLABTestFiles))""
        env:
          MLM_LICENSE_TOKEN: $(MLM_LICENSE_TOKEN)
        displayName: 'Download matlab-batch for Linux'

  - job: ParallelMac
    # Matrix strategy to run builds across different OS and MATLAB release combinations
    # strategy:
    #   parallel: 3
    pool:
      vmImage: macOS-latest
    steps:
      # Install MATLAB and required products
      - task: InstallMATLAB@1
        inputs:
          release: R2025a
          products: MATLAB_Compiler_SDK MATLAB_Test Simulink_Test

      - bash: chmod +x  DistributeTests.sh && ./DistributeTests.sh 
        displayName: 'Bash Script to distribute tests'

      - script: |
          echo $(MATLABTestFiles)

      # Download matlab-batch for macOS
      - bash: |
          curl -L "https://ssd.mathworks.com/supportfiles/ci/matlab-batch/v1/maci64/matlab-batch" -o matlab-batch
          chmod +x matlab-batch
          ./matlab-batch "runtests($(MATLABTestFiles))"
        env:
          MLM_LICENSE_TOKEN: $(MLM_LICENSE_TOKEN)
        displayName: 'Download matlab-batch for macOS'    