jobs:
  # - job: ParallelWindows
  #   # Matrix strategy to run builds across different OS and MATLAB release combinations
  #   strategy:
  #     parallel: 3
  #   pool:
  #     vmImage: windows-latest
  #   steps:
  #     # Install MATLAB and required products
  #     - task: InstallMATLAB@1
  #       inputs:
  #         release: R2025a
  #         products: MATLAB_Compiler_SDK MATLAB_Test Simulink_Test

  #     - powershell: .\DistributeTests.ps1 
  #       displayName: 'PowerShell Script to distribute tests'

  #     - script: |
  #         echo $(MLM_LICENSE_TOKEN)
  #       env:
  #         MLM_LICENSE_TOKEN: $(MLM_LICENSE_TOKEN)
      
  #      # Download matlab-batch.exe for Windows
  #     - powershell: |
  #         Invoke-WebRequest -Uri "https://ssd.mathworks.com/supportfiles/ci/matlab-batch/v1/win64/matlab-batch.exe" -OutFile "matlab-batch.exe"
  #       displayName: 'Download matlab-batch for Windows'

  #     - script: |
  #          matlab-batch.exe runtests($(MATLABTestFiles))
  #       env:
  #         MLM_LICENSE_TOKEN: $(MLM_LICENSE_TOKEN)

  - job: ParallelLinux
    # Matrix strategy to run builds across different OS and MATLAB release combinations
    strategy:
      parallel: 3
    pool:
      vmImage: ubuntu-latest
    steps:
      # Install MATLAB and required products
      - task: InstallMATLAB@1
        inputs:
          release: R2025a
          products: MATLAB_Compiler_SDK MATLAB_Test Simulink_Test

      - bash: ./DistributeTests.sh
        displayName: 'Bash Script to distribute tests'

      - script: |
          echo $(MATLABTestFiles)

      # Linux job
      - bash: |
          set -e
          curl -L "https://ssd.mathworks.com/supportfiles/ci/matlab-batch/v1/glnxa64/matlab-batch" -o "$HOME/matlab-batch"
          chmod +x "$HOME/matlab-batch"
          "$HOME/matlab-batch" runtests($(MATLABTestFiles))
        env:
          MLM_LICENSE_TOKEN: $(MLM_LICENSE_TOKEN)
        displayName: 'Download and run matlab-batch for Linux'

  - job: ParallelMac
    # Matrix strategy to run builds across different OS and MATLAB release combinations
    strategy:
      parallel: 3
    pool:
      vmImage: macOS-latest
    steps:
      # Install MATLAB and required products
      - task: InstallMATLAB@1
        inputs:
          release: R2025a
          products: MATLAB_Compiler_SDK MATLAB_Test Simulink_Test

      - bash: ./DistributeTests.sh 
        displayName: 'Bash Script to distribute tests'

      - script: |
          echo $(MATLABTestFiles)

      # Mac job
      - bash: |
          set -e
          curl -L "https://ssd.mathworks.com/supportfiles/ci/matlab-batch/v1/maci64/matlab-batch" -o "$HOME/matlab-batch"
          chmod +x "$HOME/matlab-batch"
          "$HOME/matlab-batch" runtests($(MATLABTestFiles))
        env:
          MLM_LICENSE_TOKEN: $(MLM_LICENSE_TOKEN)
        displayName: 'Download and run matlab-batch for macOS'