jobs:
  - job: BuildPythonPackage
    # Matrix strategy to run builds across different OS and MATLAB release combinations
    strategy:
      matrix:
        linux:
          imageName: ubuntu-latest
        # Disabled until Azure DevOps supports Apple Silicon runners
        # mac:
        #   imageName: macOS-latest
        windows:
          imageName: windows-latest
    pool:
      vmImage: $(imageName)
    steps:
      # Install MATLAB and required products
      - task: InstallMATLAB@1
        inputs:
          release: R2026b
          products: MATLAB_Compiler_SDK MATLAB_Test
      
      # Builds Python package from MATLAB function and verifies functionality through equivalence tests
      - task: RunMATLABBuild@1
        inputs:
          tasks: equivalenceTest
        env:
          MLM_LICENSE_TOKEN: $(MLM_LICENSE_TOKEN)
      
      # Store the built Python package as an artifact
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: KgToPoundsPythonBuild
          ArtifactName: KgToPounds-$(imageName)
          publishLocation: Container
