jobs:
  # - job: ParallelWindows
  #   # Parallel strategy to run tests in parallel
  #   strategy:
  #     parallel: 2
  #   pool:
  #     vmImage: windows-latest
  #   steps:
  #     # Install MATLAB and required products
  #     - task: InstallMATLAB@1
  #       inputs:
  #         release: R2025a
  #         products: MATLAB_Test Simulink_Test

  #     - powershell: .\AzureDevOps\DistributeTests.ps1
  #       displayName: 'PowerShell Script to distribute tests'

  #     - task: RunMATLABTests@1
  #       inputs:
  #         selectByName: $(MATLABTestFiles)
  #         sourceFolder: src
  #       env:
  #         MLM_LICENSE_TOKEN: $(MLM_LICENSE_TOKEN)

  - job: ParallelLinux
    # Parallel strategy to run tests in parallel
    strategy:
      parallel: 2
    pool:
      vmImage: ubuntu-latest
    steps:
      # Install MATLAB and required products
      - task: InstallMATLAB@1
        inputs:
          release: R2025a
          products: MATLAB_Compiler_SDK MATLAB_Test

      - bash: chmod +x  ./AzureDevOps/DistributeTests.sh && ./AzureDevOps/DistributeTests.sh 
        displayName: 'Bash Script to distribute tests'

      # Builds Python package from MATLAB function and verifies functionality through equivalence tests
      - task: RunMATLABBuild@1
        inputs:
          tasks: equivalenceTest
        env:
          MLM_LICENSE_TOKEN: $(MLM_LICENSE_TOKEN)
      
      - task: RunMATLABTests@1
        inputs:
          selectByName: $(MATLABTestFiles)
          sourceFolder: src
        env:
          MLM_LICENSE_TOKEN: $(MLM_LICENSE_TOKEN)    

  # - job: ParallelMac
  #   # Parallel strategy to run tests in parallel
  #   strategy:
    #   parallel: 2
    # pool:
    #   vmImage: macOS-latest
    # steps:
    #   # Install MATLAB and required products
    #   - task: InstallMATLAB@1
    #     inputs:
    #       release: R2025a
    #       products: MATLAB_Test Simulink_Test

    #   - bash: chmod +x  ./AzureDevOps/DistributeTests.sh && ./AzureDevOps/DistributeTests.sh 
    #     displayName: 'Bash Script to distribute tests'

    #   - task: RunMATLABTests@1
    #     inputs:
    #       selectByName: $(MATLABTestFiles)
    #       sourceFolder: src
    #     env:
    #       MLM_LICENSE_TOKEN: $(MLM_LICENSE_TOKEN)       