jobs:
  # This job compiles MEX files and runs tests across different platforms
  - job: CompileAndTestMex
    strategy:
      matrix:
        linux:
          imageName: ubuntu-latest
        mac:
          imageName: macOS-latest
        # windows:
        #   imageName: windows-latest
    pool:
      vmImage: $(imageName)
    steps:

      # - script: |
      #     echo $PATH
      #     # export PATH='$(MATLABROOT)'/bin:$PATH
      #     # echo $PATH
      #     ls
      #     which matlab
      #   env:
      #     PATH: "$(MATLABROOT)/bin:$(PATH)"
          
      # - script: |
      #     cd '$(MATLABROOT)'/bin
      #     ls
      #     which matlab
      #   env:
      #     PATH: "$(MATLABROOT)/bin:$(PATH)"
        
      - task: InstallMATLAB@1
        condition: ne(variables.CACHE_RESTORED, 'true')

      # - task: Cache@2
      #   inputs:
      #     key: "$(imageName)"
      #     restoreKeys: |
      #        "$(imageName)"
      #     path: "$(MATLABROOT)"
      #     cacheHitVar: CACHE_RESTORED
      #   displayName: Cache MATLAB

      - task: RunMATLABCommand@1
        inputs:
          command: "fid = fopen('matlabroot.txt','w'); fprintf(fid, '%s', matlabroot); fclose(fid);"
        env:
          PATH: "$(MATLABROOT)/bin:$(PATH)"

      # - script: MATLAB_CACHE_FOLDER=$(matlab-batch matlabroot)
      # - script: echo "Hello"
      #   ${{ if eq(variables['imageName'], 'windows-latest') }}:
      - script: |
          # export MATLAB_CACHE_FOLDER=$(cat matlabroot.txt)
          # echo $(MATLAB_CACHE_FOLDER)
          # echo "##vso[task.setvariable variable=matlab.cache.folder]MATLAB_CACHE_FOLDER"
          # matlab -batch "disp(matlabroot)" > matroot.txt
          MATLABROOT=$(tail -n 1 matlabroot.txt)
          echo "##vso[task.setvariable variable=MATLABROOT]$MATLABROOT"
          # echo "MATLAB_CACHE_FOLDER=$MATLAB_CACHE_FOLDER" >> $BASH_ENV
      # - script: $MATLAB_CACHE_FOLDER = matlab-batch matlabroot
      #   env:
      #     MLM_LICENSE_TOKEN: $(MLM_LICENSE_TOKEN)
        # ${{ else }}:
        #   - script: set MATLAB_CACHE_FOLDER=$(matlab-batch matlabroot)
        #     env:
        #       MLM_LICENSE_TOKEN: $(MLM_LICENSE_TOKEN)
      - script: echo $(MATLABROOT)

      # Runs build to create MEX file and then run tests
      - task: RunMATLABBuild@1
        inputs:
          tasks: test
        env:
          MLM_LICENSE_TOKEN: $(MLM_LICENSE_TOKEN)
      
      # Uploads the test results
      - publish: 'test-results/results.xml'
        artifact: 'test-results-$(imageName)'
      
      # Saves MEX files for the packaging job
      - task: CopyFiles@2
        inputs:
          SourceFolder: 'toolbox'
          Contents: '**/*.mex*'
          TargetFolder: toolbox/tmpMexFolder
      - publish: 'toolbox/tmpMexFolder'
        artifact: mex-$(imageName)

  # This job packages and releases the toolbox after successful MEX compilation
  - job: CreateAndReleaseToolbox
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: InstallMATLAB@1
      
      # Downloads all mex files from previous job
      - task: DownloadPipelineArtifact@2
        inputs:
          itemPattern: 'mex-*/*'
          targetPath: 'tmpMexFolder'
      - task: CopyFiles@2
        inputs:
          SourceFolder: 'tmpMexFolder'
          Contents: '**/*.mex*'
          flattenFolders: true
          targetFolder: 'toolbox'
      
      # Packages all files in toolbox folder into a mltbx toolbox package
      - task: RunMATLABBuild@1
        inputs:
          tasks: packageToolbox
        env:
          MLM_LICENSE_TOKEN: $(MLM_LICENSE_TOKEN)
      
      # The packaged toolbox is distributed as a GitHub release
      - task: GitHubRelease@1
        inputs:
          gitHubConnection: advanced-ci-configuration-examples
          title: "Cross-Platform Array Product Toolbox"
          assets: 'toolbox.mltbx'
          tagSource: 'userSpecifiedTag'
          tag: '$(Build.BuildNumber)'
    dependsOn: CompileAndTestMex
