jobs:
  # This job compiles MEX files and runs tests across different platforms
  - job: CompileAndTestMex
    strategy:
      matrix:
        linux:
          imageName: ubuntu-latest
        mac:
          imageName: macOS-latest
        # windows:
        #   imageName: windows-latest
    pool:
      vmImage: $(imageName)
    steps:
      - task: Cache@2
        inputs:
          key: "$(imageName)"
          # restoreKeys: |
          #    "$(imageName)"
          path: $(MATLABROOT)
          cacheHitVar: MATLAB_CACHE_RESTORED
        displayName: Cache MATLAB

      - script: |
          ls

      # need to check inside extension
      # condition: ne(variables.MATLAB_CACHE_RESTORED, 'true')
      - task: InstallMATLAB@1

      - task: RunMATLABCommand@1
        inputs:
          command: "fid = fopen('matlabroot.txt','w'); fprintf(fid, '%s', matlabroot); fclose(fid);"
        # if cache restored not checked, the user will need to provide updated PATH at every step
        # env:
        #   PATH: "$(MATLABROOT)/bin:$(PATH)"

      - script: |
          MATLABROOT=$(tail -n 1 matlabroot.txt)
          echo "##vso[task.setvariable variable=MATLABROOT]$MATLABROOT"
      - script: echo $(MATLABROOT)

      # # Runs build to create MEX file and then run tests
      # - task: RunMATLABBuild@1
      #   inputs:
      #     tasks: test
      #   env:
      #     MLM_LICENSE_TOKEN: $(MLM_LICENSE_TOKEN)
      
      # # Uploads the test results
      # - publish: 'test-results/results.xml'
      #   artifact: 'test-results-$(imageName)'
      
      # # Saves MEX files for the packaging job
      # - task: CopyFiles@2
      #   inputs:
      #     SourceFolder: 'toolbox'
      #     Contents: '**/*.mex*'
      #     TargetFolder: toolbox/tmpMexFolder
      # - publish: 'toolbox/tmpMexFolder'
      #   artifact: mex-$(imageName)

  # This job packages and releases the toolbox after successful MEX compilation
  - job: CreateAndReleaseToolbox
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: InstallMATLAB@1
      
      # Downloads all mex files from previous job
      - task: DownloadPipelineArtifact@2
        inputs:
          itemPattern: 'mex-*/*'
          targetPath: 'tmpMexFolder'
      - task: CopyFiles@2
        inputs:
          SourceFolder: 'tmpMexFolder'
          Contents: '**/*.mex*'
          flattenFolders: true
          targetFolder: 'toolbox'
      
      # Packages all files in toolbox folder into a mltbx toolbox package
      - task: RunMATLABBuild@1
        inputs:
          tasks: packageToolbox
        env:
          MLM_LICENSE_TOKEN: $(MLM_LICENSE_TOKEN)
      
      # The packaged toolbox is distributed as a GitHub release
      - task: GitHubRelease@1
        inputs:
          gitHubConnection: advanced-ci-configuration-examples
          title: "Cross-Platform Array Product Toolbox"
          assets: 'toolbox.mltbx'
          tagSource: 'userSpecifiedTag'
          tag: '$(Build.BuildNumber)'
    dependsOn: CompileAndTestMex
